version: '3.3'

services:
  app:
    build: ./
    working_dir: /app
    volumes:
      - ".:/app:cached"
    ports:
      - 9229:9229 #On ouvre le port 9229 qui est le port de debug par défaut
      - 3000:3000 